
apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    svc: cluster
spec:
  selector:
    app: location
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort